################################################################
## REQUIRED PARAMETERS
author: "Claire Rioualen"
  qsub: "-V -m a -d ."                                                  # Required, even if empty quotes
  genome:
    organism: "Saccharomyces cerevisiae"
    size: "12500000"
    version: "sacCer3"
    fasta_file: "Saccharomyces_cerevisiae.R64-1-1.30.dna.genome.fa"
    gff3_file: "Saccharomyces_cerevisiae.R64-1-1.30.gff3"
    gtf_file: "Saccharomyces_cerevisiae.R64-1-1.30.gtf"
#    fasta_url: "http://hgdownload.soe.ucsc.edu/goldenPath/sacCer1/bigZips/chromFa.zip"

  metadata:
    samples: "SnakeChunks/examples/ChIP-seq_GSE55357/samples.tab"       # Contains at least an "ID" column
    design: "SnakeChunks/examples/ChIP-seq_GSE55357/design.tab"         # Contains 2 columns with ID or groups of samples to be compared
    configfile: "SnakeChunks/examples/ChIP-seq_GSE55357/config.yml"     # Required for flowcharts generation; should be revised
    seq_type: "se"

  dir:
    reads_source: "data"                                                # Raw data (sra)
    fastq: "fastq"                                                      # Fastq location, either raw data or converted sra files 
    genome: "genome"                                                    # Location of the genome files (fasta, gff3, gtf) or symlink to location
    results: "results"
    snakechunks: "SnakeChunks"                                          # Location of the library or symlink to library

    samples: "results/samples"
    diffexpr: "results/diffexpr"
    reports: "results/reports"

  tools:
    trimming: ""
    mapping: "bowtie2"
    peakcalling: "macs2 homer"
    annotation: "intersect"

################################################################
## OPTIONAL PARAMETERS
##
## These are the parameters that are used by rules & programs. 
## They all have default parameters, so everything below is optional. 
  bowtie2:
    threads: "10"                                                       # Default 1
    max_mismatches: "0"                                                 # Default 0 (0 or 1 only)

  macs2: 
    qval: "0.001"                                                       # Default 0.05
    keep_dup: "all"                                                     # Default 1
    mfold_min: "2"                                                      # Default 5
    mfold_max: "50"                                                     # Default 50
    other_options: "--call-summits"                                     # optional can include --call-summits, --broad...

  homer: 
    style: "factor"                                                     # Default 'factor'; else 'histone', 'groseq', 'tss', 'dnase', 'super', 'mC' (beware of output filenames)
    F: "2"                                                              # Default 4
    L: "2"                                                              # Default 4
    P: "0.05"                                                           # Default 0.0001
    fdr: "0.05"                                                         # Default 0.001

