################################################################
## REQUIRED PARAMETERS
  author: "Claire Rioualen"
  qsub: "-V -m a -d ."                                                  # Required, even if empty quotes
  genome:
    organism: "Saccharomyces cerevisiae"
    size: "12500000"
    version: "sacCer3"
    fasta_file: "Saccharomyces_cerevisiae.R64-1-1.30.dna.genome.fa"
    gff3_file: "Saccharomyces_cerevisiae.R64-1-1.30.gff3"
    gtf_file: "Saccharomyces_cerevisiae.R64-1-1.30.gtf"

  metadata:
    samples: "SnakeChunks/examples/RNA-seq_GSE55316/samples.tab"       # Contains at least an "ID" column
    design: "SnakeChunks/examples/RNA-seq_GSE55316/design.tab"         # Contains 2 columns with ID or groups of samples to be compared
    configfile: "SnakeChunks/examples/RNA-seq_GSE55316/config.yml"     # Required for flowcharts generation; should be revised
    seq_type: "se"

  dir:
    reads_source: "data"                                                # Raw data (sra)
    fastq: "fastq"                                                      # Fastq location, either raw data or converted sra files 
    genome: "genome"                                                    # Location of the genome files (fasta, gff3, gtf) or symlink to location
    results: "results"
    snakechunks: "SnakeChunks"                                          # Location of the library or symlink to library

    samples: "results/samples"
    diffexpr: "results/diffexpr"
    reports: "results/reports"

  trimming: ""
  mapping: "tophat"
  read_counts: "featureCounts"
  diffexpr: "DESeq2"

################################################################
## OPTIONAL PARAMETERS
##
## These are the parameters that are used by rules & programs. 
##
## If nothing is mentionned  below, all prgrams will use their default parameters. 
  tophat:
    max_mismatches: 1                                                   # Default 2
    threads: 6                                                          # Default 1

  subread-featureCounts:
    attr_type: "gene_id"                                                # Default 'gene_id'
    feature_type: "exon"
    strand_specificity: 1                                               # Strand-specific read counting, 0 (unstranded)(default), 1 (stranded) or 2 (reversely stranded)
    multi_mapping: ""

  edgeR:
    featuresToRemove: "NULL"
    varInt: "group"
    condRef: "WT"
    batch: NULL
    alpha: "0.05"
    pAdjustMethod: "BH"
    cpmCutoff: "1"
    gene_selection: "pairwise"
    normalizationMethod: "TMM"

  DESeq2:
    featuresToRemove: NULL                                              # "alignment_not_unique", "ambiguous", "no_feature", "not_aligned", "too_low_aQual"
    varInt: "group"
    condRef: "WT"
    batch: "NULL"
    fitType: "parametric"                                               # "parametric" (default) or "local"
    cooksCutoff: "TRUE"
    independentFiltering: "TRUE"
    alpha: "0.05"
    pAdjustMethod: "BH"                                                 # "BH" (default) or "BY"
    typeTrans: "VST"                                                    # "VST" or "rlog"
    locfunc: "median"                                                   # "median" (default) or "shorth" to estimate the size factors

