---
  description: |
    This config file is designed to work with the workflow factor_workflow.py.

    Note\: yaml format prohibits using tabulations.

    Optional parameters, if not provided, are automatically set to the default value provided with the given program.

  title: "RNA-Seq of Escherichia coli after anaerobic-aerobic transition"
  author: "Claire Rioualen & Jacques van Helden"
  qsub: "-V -m a -d ."  # qsub options, which should be adapted to the local configuration
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"                                                          # required. has to match genome filenames and directories
    size: "4639221"
    fasta_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.dna.genome.fa" 
    gff3_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gff3"
    gtf_file: "Escherichia_coli_str_k_12_substr_mg1655.GCA_000005845.1.21.gtf"


  metadata: 
    samples: "gene-regulation/examples/RNA-seq_SE_GSE71562/samples.tab"                                     # required. has to contain at least sample ids
    design: "gene-regulation/examples/RNA-seq_SE_GSE71562/design.tab"                                       # required. has to contain at least ids of pairs of samples to be compared
    configfile: "gene-regulation/examples/RNA-seq_SE_GSE71562/config.yml"                                   # required for flowcharts generation; maybe this should be revised
    seq_type: "se"

  dir:
    reads_source: "data"                                                                                    # required. dir containing raw data organized in sub directories named after the samples
    fastq: "fastq"
    genome: "genome"                                                                                        # required. where to store genomes
    results: "results"                                                                                      # required. dir for all result files that are produced by the pipeline
    gene_regulation: "gene-regulation"                                                                      # required. location of the snakemake library

    samples: "results/samples"                                                                              # optional. will hold sample treatment (trimming, alignment, QC...).    If not mentioned, will be config["dir"]["results"]
    diffexpr: "results/diffexpr"                                                                            # optional. will hold the results of differential expression analysis.  If not mentioned, will be config["dir"]["results"]
    reports: "results/reports"                                                                              # optional. will hold reports and graphics.                             If not mentioned, will be config["dir"]["results"]

  tools:
    trimming: ""
    mapping: "bowtie2 subread-align" # tophat"
    diffexpr: "edgeR DESeq2"
    read_counts: "featureCounts"
    infer_transcripts: "cufflinks"

  bowtie2:
    max_mismatches: "1"
    threads: "10"

  subread:
    max_mismatches: "1"
    threads: "10"

  bowtie:
    max_mismatches: "1"
    threads: "10"

  bwa:
    max_mismatches: "1"
    threads: "10"

  tophat:
    max_mismatches: "1"
    threads: "10"

  cufflinks:
    threads: "4"
    libtype: "fr-firststrand"

  edgeR:
    featuresToRemove: "NULL"
    varInt: "group"
    condRef: "t10"
    batch: NULL
    alpha: "0.05"
    pAdjustMethod: "BH"
    cpmCutoff: "1"
    gene_selection: "pairwise"
    normalizationMethod: "TMM"

  DESeq2:
    featuresToRemove: NULL                          # c("alignment_not_unique", "ambiguous", "no_feature", "not_aligned", "too_low_aQual")
    varInt: "group"
    condRef: "t10"
    batch: "NULL"
    fitType: "parametric"                           # "parametric" (default) or "local"
    cooksCutoff: "TRUE"
    independentFiltering: "TRUE"
    alpha: "0.05"
    pAdjustMethod: "BH"                             # "BH" (default) or "BY"
    typeTrans: "VST"                                # "VST" or "rlog"
    locfunc: "median"                               # "median" (default) or "shorth" to estimate the size factors


