---
  RNA_seq:
    snakefile: "RNA-seq_workflow_PE.py"
    configfile: "gene-regulation/examples/RNA-seq_PE_GSE41190/config.yml"
    directory: "/data/analyses/RNA-seq_PE_GSE41190"

  ChIP_seq:
    snakefile: "ChIP-seq_workflow_SE.py"
    configfile: "gene-regulation/examples/ChIP-seq_SE_GSE41187/config.yml"
    directory: "/data/analyses/ChIP-seq_SE_GSE41187"

  snakemake:
    workflows: "gene-regulation/scripts/snakefiles/workflows"
    rules: "gene-regulation/scripts/snakefiles/rules"
