  RNA_seq:
    snakefile: "gene-regulation/scripts/workflows/RNA-seq.wf"
    configfile: "gene-regulation/examples/RNA-seq_GSE55316/config.yml"
    directory: "RNA-seq_GSE55316"

  ChIP_seq:
    snakefile: "gene-regulation/scripts/workflows/ChIP-seq.wf"
    configfile: "gene-regulation/examples/ChIP-seq_GSE55357/config.yml"
    directory: "ChIP-seq_GSE55357"

#  snakemake:
#    workflows: "gene-regulation/scripts/snakefiles/workflows"
#    rules: "gene-regulation/scripts/snakefiles/rules"
