################################################################
## REQUIRED PARAMETERS
  author: "Claire Rioualen"
  qsub: "-V -m a -d ."                                                  # Required, even if empty quotes
  genome:
    organism: "Saccharomyces cerevisiae"
    size: "12500000"
    version: "sacCer3"
    fasta_file: "Saccharomyces_cerevisiae.R64-1-1.30.dna.genome.fa"
    gff3_file: "Saccharomyces_cerevisiae.R64-1-1.30.gff3"
    gtf_file: "Saccharomyces_cerevisiae.R64-1-1.30.gtf"
#    fasta_url: "http://hgdownload.soe.ucsc.edu/goldenPath/sacCer1/bigZips/chromFa.zip"

  metadata:
    samples: "SnakeChunks/examples/ChIP-seq_SE_GSE20870/samples.tab"       # Contains at least an "ID" column
    design: "SnakeChunks/examples/ChIP-seq_SE_GSE20870/design.tab"         # Contains 2 columns with ID or groups of samples to be compared
    configfile: "SnakeChunks/examples/ChIP-seq_SE_GSE20870/config.yml"     # Required for flowcharts generation; should be revised
    seq_type: "se"

  dir:
    reads_source: "data"                                                # Raw data (sra)
    fastq: "fastq"                                                      # Fastq location, either raw data or converted sra files 
    genome: "genome"                                                    # Location of the genome files (fasta, gff3, gtf) or symlink to location
    results: "results"
    snakechunks: "SnakeChunks"                                          # Location of the library or symlink to library

    samples: "results/samples"
    peaks: "results/peaks"
    reports: "results/reports"

  tools:
    trimming: "sickle cutadapt"
    mapping: "bowtie2 subread-align bowtie bwa"
    peakcalling: "macs2 macs14 homer spp swembl mosaics" # bPeaks"
    annotation: "intersect" # window closest"

################################################################
## OPTIONAL PARAMETERS
##
## These are the parameters that are used by rules & programs. 
## They all have default parameters, so everything below is optional. 
  sickle:
    qual_threshold: "20"                                                # Default 20
    length_threshold: "20"                                              # Default 20

  cutadapt:
    qual_threshold: "20"                                                # Default 20
    length_threshold: "20"                                              # Default 20

  bwa: 
    threads: "10"                                                       # Default 1

  bowtie2:
    threads: "10"                                                       # Default 1
    max_mismatches: "0"                                                 # Default 0 (0 or 1 only)

  subread-align:
    threads: "10"                                                       # Default 1
    max_mismatches: "3"                                                 # Default 3

  macs14:
    pval: "0.00001"                                                     # Default 0.00001
    mfold: "5,30"                                                       # Default 10,30
    keep_dup: "auto"                                                    # Default auto, else int
    bandwidth: "300"                                                    # Default 300
    other_options: "--nomodel"                                          # Include -bdg (time-consuming), -wig (time-consuming), --call-summits (requires PeakSplitter)

  macs2: 
    qval: "0.001"                                                       # Default 0.05
    keep_dup: "all"                                                     # Default 1
    mfold_min: "2"                                                      # Default 5
    mfold_max: "50"                                                     # Default 50
    other_options: "--call-summits"                                     # optional can include --call-summits, --broad...

  swembl:
    R: "0.5"                                                            # Relative background (depends on -N). Default 0
    N: "1000000"                                                        # Number of input reads. Default 0
    x: "1.2"                                                            # Penalty factor for reference reads. Default 1

  homer: 
    style: "factor"                                                     # Default 'factor'; else 'histone', 'groseq', 'tss', 'dnase', 'super', 'mC' (beware of output filenames)
    F: "2"                                                              # Default 4
    L: "2"                                                              # Default 4
    P: "0.05"                                                           # Default 0.0001
    fdr: "0.05"                                                         # Default 0.001

  spp: 
    fdr: "0.01"                                                         # Default 0.01

  bPeaks: 
    IPcoeff: "2"                                                        # Default 2
    controlCoeff: "4"                                                   # Default 2
    log2FC: "1"                                                         # Default 2
    averageQuantiles: "0.8"                                             # Default 0.9
    windowSize: "50"                                                    # Default 150
    windowOverlap: "40"                                                 # Default 50

#  peak-motifs: 
#    tasks: "all"                                                                                                   # Default "all", incl. purge,seqlen,composition,ref_motifs,disco,meme,chipmunk,merge_words,motifs_vs_ref,motifs_vs_db,timelog,synthesis) (what about collect_motifs,motifs_vs_motifs,archive,small_summary,scan ?...)
#    max_seq_len: "0"                                                                                               # default ? curr not used
#    motif_db: "Yeastract tf $RSAT/public_html/motif_databases/Yeastract/yeastract_20150629.tf "                    # Required. name format db_file
#    disco: "oligos,positions,dyads"                                                                                # default ? oligos|dyads|positions|local_words|merged_words|meme|chipmunk


